require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') });

const db = require('../config/database');

const animals = [
  // ── COMMON (15) ─────────────────────────────────────────────────────────────
  {
    common_name: 'House Crow',
    scientific_name: 'Corvus splendens',
    category: 'bird',
    rarity: 'common',
    base_points: 10,
    iucn_status: 'LC',
    description: 'A widespread, adaptable crow found throughout South Asia. Recognizable by its grey neck and black body.',
    habitat: 'Urban areas, villages, farmland',
    typical_regions: ['Nepal', 'India', 'Bangladesh', 'Sri Lanka', 'Pakistan'],
    ai_labels: ['house crow', 'Corvus splendens', 'crow', 'grey-necked crow'],
  },
  {
    common_name: 'House Sparrow',
    scientific_name: 'Passer domesticus',
    category: 'bird',
    rarity: 'common',
    base_points: 10,
    iucn_status: 'LC',
    description: 'One of the world\'s most familiar birds, closely associated with human habitation.',
    habitat: 'Urban and suburban areas, farmland',
    typical_regions: ['Nepal', 'India', 'Pakistan', 'Bangladesh', 'Global'],
    ai_labels: ['house sparrow', 'Passer domesticus', 'sparrow'],
  },
  {
    common_name: 'Common Myna',
    scientific_name: 'Acridotheres tristis',
    category: 'bird',
    rarity: 'common',
    base_points: 10,
    iucn_status: 'LC',
    description: 'A bold, noisy bird with a yellow beak and eye-patch. Often seen foraging on the ground.',
    habitat: 'Urban areas, open countryside, farmland',
    typical_regions: ['Nepal', 'India', 'Bangladesh', 'Sri Lanka'],
    ai_labels: ['common myna', 'Indian myna', 'Acridotheres tristis', 'myna'],
  },
  {
    common_name: 'Rock Pigeon',
    scientific_name: 'Columba livia',
    category: 'bird',
    rarity: 'common',
    base_points: 10,
    iucn_status: 'LC',
    description: 'The ancestor of all domestic pigeons. Found in cities and cliffs worldwide.',
    habitat: 'Urban areas, cliffs, coastal regions',
    typical_regions: ['Nepal', 'India', 'Global'],
    ai_labels: ['rock pigeon', 'feral pigeon', 'Columba livia', 'pigeon'],
  },
  {
    common_name: 'Spotted Deer',
    scientific_name: 'Axis axis',
    category: 'mammal',
    rarity: 'common',
    base_points: 10,
    iucn_status: 'LC',
    description: 'Also called the chital, this graceful deer has a spotted coat year-round. Common in national parks.',
    habitat: 'Grasslands, deciduous forests, scrubland',
    typical_regions: ['Nepal', 'India', 'Sri Lanka'],
    ai_labels: ['spotted deer', 'chital', 'Axis axis', 'chital deer'],
  },
  {
    common_name: 'Indian Pond Heron',
    scientific_name: 'Ardeola grayii',
    category: 'bird',
    rarity: 'common',
    base_points: 10,
    iucn_status: 'LC',
    description: 'A stocky heron with streaked brownish plumage, common near water bodies and paddy fields.',
    habitat: 'Wetlands, paddy fields, ponds',
    typical_regions: ['Nepal', 'India', 'Bangladesh'],
    ai_labels: ['Indian pond heron', 'Ardeola grayii', 'pond heron', 'paddy bird'],
  },
  {
    common_name: 'Common Kingfisher',
    scientific_name: 'Alcedo atthis',
    category: 'bird',
    rarity: 'common',
    base_points: 10,
    iucn_status: 'LC',
    description: 'A jewel-like bird with brilliant blue-orange plumage, diving into rivers and streams for fish.',
    habitat: 'Rivers, streams, ponds',
    typical_regions: ['Nepal', 'India', 'Europe', 'Asia'],
    ai_labels: ['common kingfisher', 'Alcedo atthis', 'kingfisher', 'Eurasian kingfisher'],
  },
  {
    common_name: 'Rhesus Macaque',
    scientific_name: 'Macaca mulatta',
    category: 'mammal',
    rarity: 'common',
    base_points: 10,
    iucn_status: 'LC',
    description: 'One of the most familiar primates in Asia. Often seen near temples and human settlements.',
    habitat: 'Forests, urban areas, temple surroundings',
    typical_regions: ['Nepal', 'India', 'China', 'Southeast Asia'],
    ai_labels: ['rhesus macaque', 'Macaca mulatta', 'rhesus monkey', 'macaque'],
  },
  {
    common_name: 'Wild Boar',
    scientific_name: 'Sus scrofa',
    category: 'mammal',
    rarity: 'common',
    base_points: 10,
    iucn_status: 'LC',
    description: 'A heavily built omnivore with coarse grey-brown fur and sharp tusks. Often seen at dusk.',
    habitat: 'Forests, grasslands, agricultural land',
    typical_regions: ['Nepal', 'India', 'Europe', 'Asia'],
    ai_labels: ['wild boar', 'Sus scrofa', 'feral pig', 'wild pig'],
  },
  {
    common_name: 'Oriental Magpie-Robin',
    scientific_name: 'Copsychus saularis',
    category: 'bird',
    rarity: 'common',
    base_points: 10,
    iucn_status: 'LC',
    description: 'A popular songbird with striking black-and-white plumage. National bird of Bangladesh.',
    habitat: 'Gardens, forests, farmland',
    typical_regions: ['Nepal', 'India', 'Bangladesh', 'Southeast Asia'],
    ai_labels: ['Oriental magpie-robin', 'Copsychus saularis', 'magpie robin', 'doel'],
  },
  {
    common_name: 'Indian Flying Fox',
    scientific_name: 'Pteropus giganteus',
    category: 'mammal',
    rarity: 'common',
    base_points: 10,
    iucn_status: 'LC',
    description: 'The largest bat in the Indian subcontinent, with a wingspan up to 1.5 m. Roosts in large colonies.',
    habitat: 'Forests, urban trees, wetland edges',
    typical_regions: ['Nepal', 'India', 'Sri Lanka'],
    ai_labels: ['Indian flying fox', 'Pteropus giganteus', 'flying fox', 'fruit bat'],
  },
  {
    common_name: 'Common Mongoose',
    scientific_name: 'Herpestes edwardsii',
    category: 'mammal',
    rarity: 'common',
    base_points: 10,
    iucn_status: 'LC',
    description: 'Famous for snake-fighting ability. A slender, quick-moving carnivore of grasslands and scrub.',
    habitat: 'Scrubland, grasslands, farms, rocky areas',
    typical_regions: ['Nepal', 'India', 'Sri Lanka', 'Pakistan'],
    ai_labels: ['Indian grey mongoose', 'Herpestes edwardsii', 'mongoose'],
  },
  {
    common_name: 'Red-vented Bulbul',
    scientific_name: 'Pycnonotus cafer',
    category: 'bird',
    rarity: 'common',
    base_points: 10,
    iucn_status: 'LC',
    description: 'A lively garden bird with a black head and distinctive red vent patch.',
    habitat: 'Gardens, forests, scrubland',
    typical_regions: ['Nepal', 'India', 'Bangladesh', 'Sri Lanka'],
    ai_labels: ['red-vented bulbul', 'Pycnonotus cafer', 'bulbul'],
  },
  {
    common_name: 'Indian Peafowl',
    scientific_name: 'Pavo cristatus',
    category: 'bird',
    rarity: 'common',
    base_points: 15,
    iucn_status: 'LC',
    description: 'The national bird of India, famous for the male\'s spectacular iridescent tail feathers.',
    habitat: 'Forests, farmland, national parks',
    typical_regions: ['Nepal', 'India', 'Sri Lanka'],
    ai_labels: ['Indian peafowl', 'Pavo cristatus', 'peacock', 'peahen'],
  },
  {
    common_name: 'Jungle Cat',
    scientific_name: 'Felis chaus',
    category: 'mammal',
    rarity: 'common',
    base_points: 15,
    iucn_status: 'LC',
    description: 'A medium-sized wild cat with no spots on its tawny body. More common than many realize.',
    habitat: 'Grasslands, wetlands, reed beds, forests',
    typical_regions: ['Nepal', 'India', 'Middle East', 'Central Asia'],
    ai_labels: ['jungle cat', 'Felis chaus', 'reed cat', 'swamp cat'],
  },

  // ── UNCOMMON (15) ────────────────────────────────────────────────────────────
  {
    common_name: 'Monitor Lizard',
    scientific_name: 'Varanus bengalensis',
    category: 'reptile',
    rarity: 'uncommon',
    base_points: 25,
    iucn_status: 'LC',
    description: 'The Bengal monitor is a large lizard reaching 175 cm. An ambush predator near water.',
    habitat: 'Forests, wetlands, agricultural areas',
    typical_regions: ['Nepal', 'India', 'Bangladesh', 'Sri Lanka'],
    ai_labels: ['Bengal monitor', 'Varanus bengalensis', 'monitor lizard', 'water monitor'],
  },
  {
    common_name: 'King Cobra',
    scientific_name: 'Ophiophagus hannah',
    category: 'reptile',
    rarity: 'uncommon',
    base_points: 30,
    iucn_status: 'VU',
    description: 'The world\'s longest venomous snake, capable of raising its head 1.8 m off the ground.',
    habitat: 'Dense highland forests, bamboo thickets',
    typical_regions: ['Nepal', 'India', 'Southeast Asia'],
    ai_labels: ['king cobra', 'Ophiophagus hannah', 'hamadryad'],
  },
  {
    common_name: 'Sloth Bear',
    scientific_name: 'Melursus ursinus',
    category: 'mammal',
    rarity: 'uncommon',
    base_points: 35,
    iucn_status: 'VU',
    description: 'A shaggy-coated bear with a long muzzle adapted for eating insects and fruit.',
    habitat: 'Dry tropical forests, grasslands, scrubland',
    typical_regions: ['Nepal', 'India', 'Sri Lanka'],
    ai_labels: ['sloth bear', 'Melursus ursinus', 'labiated bear'],
  },
  {
    common_name: 'Smooth-coated Otter',
    scientific_name: 'Lutrogale perspicillata',
    category: 'mammal',
    rarity: 'uncommon',
    base_points: 25,
    iucn_status: 'VU',
    description: 'A large, social otter with a distinctive smooth coat. Active during the day along rivers.',
    habitat: 'Rivers, lakes, mangroves',
    typical_regions: ['Nepal', 'India', 'Southeast Asia'],
    ai_labels: ['smooth-coated otter', 'Lutrogale perspicillata', 'smooth otter'],
  },
  {
    common_name: 'Mugger Crocodile',
    scientific_name: 'Crocodylus palustris',
    category: 'reptile',
    rarity: 'uncommon',
    base_points: 30,
    iucn_status: 'VU',
    description: 'A broad-snouted crocodile found in freshwater lakes and rivers across South Asia.',
    habitat: 'Freshwater lakes, rivers, marshes',
    typical_regions: ['Nepal', 'India', 'Sri Lanka', 'Pakistan'],
    ai_labels: ['mugger crocodile', 'Crocodylus palustris', 'marsh crocodile', 'mugger'],
  },
  {
    common_name: 'Indian Cobra',
    scientific_name: 'Naja naja',
    category: 'reptile',
    rarity: 'uncommon',
    base_points: 25,
    iucn_status: 'LC',
    description: 'The spectacled cobra with a distinctive hood marking. A medically important species.',
    habitat: 'Forests, farmland, urban fringes',
    typical_regions: ['Nepal', 'India', 'Bangladesh', 'Sri Lanka'],
    ai_labels: ['Indian cobra', 'Naja naja', 'spectacled cobra', 'Asian cobra'],
  },
  {
    common_name: 'Himalayan Tahr',
    scientific_name: 'Hemitragus jemlahicus',
    category: 'mammal',
    rarity: 'uncommon',
    base_points: 30,
    iucn_status: 'NT',
    description: 'A robust wild goat native to the Himalayas, with thick reddish-brown fur.',
    habitat: 'Rocky Himalayan slopes, alpine meadows',
    typical_regions: ['Nepal', 'India (Himalayan states)'],
    ai_labels: ['Himalayan tahr', 'Hemitragus jemlahicus', 'tahr'],
  },
  {
    common_name: 'Rufous-bellied Eagle',
    scientific_name: 'Lophotriorchis kienerii',
    category: 'bird',
    rarity: 'uncommon',
    base_points: 25,
    iucn_status: 'LC',
    description: 'A small but boldly patterned forest eagle with a deep chestnut belly.',
    habitat: 'Subtropical and tropical forests',
    typical_regions: ['Nepal', 'India', 'Southeast Asia'],
    ai_labels: ['rufous-bellied eagle', 'Lophotriorchis kienerii', 'chestnut-bellied eagle'],
  },
  {
    common_name: 'Golden Jackal',
    scientific_name: 'Canis aureus',
    category: 'mammal',
    rarity: 'uncommon',
    base_points: 25,
    iucn_status: 'LC',
    description: 'An omnivorous canine that is highly adaptable, often heard howling at dusk.',
    habitat: 'Grasslands, forests, open country',
    typical_regions: ['Nepal', 'India', 'Eastern Europe', 'Middle East'],
    ai_labels: ['golden jackal', 'Canis aureus', 'jackal', 'Asiatic jackal'],
  },
  {
    common_name: 'Sambar Deer',
    scientific_name: 'Rusa unicolor',
    category: 'mammal',
    rarity: 'uncommon',
    base_points: 25,
    iucn_status: 'VU',
    description: 'The largest deer in Asia, with impressive antlers in males. A key prey species for tigers.',
    habitat: 'Dense forests, hills, wetland edges',
    typical_regions: ['Nepal', 'India', 'Sri Lanka', 'Southeast Asia'],
    ai_labels: ['sambar deer', 'Rusa unicolor', 'sambar', 'sambhur'],
  },
  {
    common_name: 'Indian Star Tortoise',
    scientific_name: 'Geochelone elegans',
    category: 'reptile',
    rarity: 'uncommon',
    base_points: 30,
    iucn_status: 'VU',
    description: 'A beautifully patterned tortoise with a star-like radiating design on each scute.',
    habitat: 'Dry grasslands, scrub forests',
    typical_regions: ['Nepal (Terai)', 'India', 'Sri Lanka', 'Pakistan'],
    ai_labels: ['Indian star tortoise', 'Geochelone elegans', 'star tortoise'],
  },
  {
    common_name: 'Himalayan Black Bear',
    scientific_name: 'Ursus thibetanus laniger',
    category: 'mammal',
    rarity: 'uncommon',
    base_points: 35,
    iucn_status: 'VU',
    description: 'The Himalayan subspecies of the Asian black bear, with a distinctive white V-shaped chest mark.',
    habitat: 'Himalayan forests, alpine scrub',
    typical_regions: ['Nepal', 'India (Himalayan states)', 'Bhutan', 'China'],
    ai_labels: ['Himalayan black bear', 'Asian black bear', 'Ursus thibetanus', 'moon bear'],
  },
  {
    common_name: 'Indian Pangolin',
    scientific_name: 'Manis crassicaudata',
    category: 'mammal',
    rarity: 'uncommon',
    base_points: 35,
    iucn_status: 'EN',
    description: 'A scaly, nocturnal insectivore and one of the world\'s most trafficked mammals.',
    habitat: 'Grasslands, forests, rocky areas',
    typical_regions: ['Nepal', 'India', 'Sri Lanka', 'Pakistan'],
    ai_labels: ['Indian pangolin', 'Manis crassicaudata', 'pangolin', 'scaly anteater'],
  },
  {
    common_name: 'Spot-billed Pelican',
    scientific_name: 'Pelecanus philippensis',
    category: 'bird',
    rarity: 'uncommon',
    base_points: 25,
    iucn_status: 'NT',
    description: 'A large water bird that nests in colonies, found on large inland lakes and wetlands.',
    habitat: 'Large inland water bodies, coastal lagoons',
    typical_regions: ['Nepal', 'India', 'Sri Lanka', 'Southeast Asia'],
    ai_labels: ['spot-billed pelican', 'Pelecanus philippensis', 'grey pelican', 'pelican'],
  },
  {
    common_name: 'Striped Hyena',
    scientific_name: 'Hyaena hyaena',
    category: 'mammal',
    rarity: 'uncommon',
    base_points: 30,
    iucn_status: 'NT',
    description: 'A solitary, mostly nocturnal scavenger of arid and semi-arid landscapes.',
    habitat: 'Dry grasslands, scrubland, rocky areas',
    typical_regions: ['Nepal (western Terai)', 'India', 'Middle East', 'Africa'],
    ai_labels: ['striped hyena', 'Hyaena hyaena', 'hyena'],
  },

  // ── RARE (10) ────────────────────────────────────────────────────────────────
  {
    common_name: 'Bengal Tiger',
    scientific_name: 'Panthera tigris tigris',
    category: 'mammal',
    rarity: 'rare',
    base_points: 75,
    iucn_status: 'EN',
    description: 'The iconic apex predator of South Asian forests. Nepal\'s Chitwan hosts a recovering population.',
    habitat: 'Tropical and subtropical moist broadleaf forests, grasslands',
    typical_regions: ['Nepal', 'India', 'Bangladesh', 'Bhutan'],
    ai_labels: ['Bengal tiger', 'Panthera tigris tigris', 'tiger', 'Royal Bengal tiger'],
  },
  {
    common_name: 'Indian One-Horned Rhinoceros',
    scientific_name: 'Rhinoceros unicornis',
    category: 'mammal',
    rarity: 'rare',
    base_points: 75,
    iucn_status: 'VU',
    description: 'The world\'s fourth-largest land animal, now mostly confined to protected areas in Nepal and India.',
    habitat: 'Tall grasslands, forests near rivers',
    typical_regions: ['Nepal', 'India (Assam)'],
    ai_labels: ['Indian rhinoceros', 'Rhinoceros unicornis', 'one-horned rhino', 'greater one-horned rhino'],
  },
  {
    common_name: 'Gharial',
    scientific_name: 'Gavialis gangeticus',
    category: 'reptile',
    rarity: 'rare',
    base_points: 75,
    iucn_status: 'CR',
    description: 'A critically endangered, fish-eating crocodilian with a distinctive bulbous snout.',
    habitat: 'Deep, fast-flowing rivers with sandy banks',
    typical_regions: ['Nepal', 'India (Chambal, Girwa, Gandak rivers)'],
    ai_labels: ['gharial', 'Gavialis gangeticus', 'gavial', 'fish-eating crocodile'],
  },
  {
    common_name: 'Himalayan Red Fox',
    scientific_name: 'Vulpes vulpes montana',
    category: 'mammal',
    rarity: 'rare',
    base_points: 60,
    iucn_status: 'LC',
    description: 'The Himalayan subspecies of the red fox, adapted to alpine conditions with denser fur.',
    habitat: 'Alpine meadows, open hillsides, rocky terrain',
    typical_regions: ['Nepal', 'India (Himalayas)', 'Tibet', 'China'],
    ai_labels: ['Himalayan red fox', 'Vulpes vulpes', 'red fox', 'mountain fox'],
  },
  {
    common_name: 'Gaur',
    scientific_name: 'Bos gaurus',
    category: 'mammal',
    rarity: 'rare',
    base_points: 65,
    iucn_status: 'VU',
    description: 'The largest bovine species in the world, with a massive muscular build.',
    habitat: 'Tropical and subtropical forests, grasslands',
    typical_regions: ['Nepal', 'India', 'Southeast Asia'],
    ai_labels: ['gaur', 'Bos gaurus', 'Indian bison', 'gayal'],
  },
  {
    common_name: 'Fishing Cat',
    scientific_name: 'Prionailurus viverrinus',
    category: 'mammal',
    rarity: 'rare',
    base_points: 70,
    iucn_status: 'VU',
    description: 'A medium-sized wild cat that dives into water to catch fish. Heavily dependent on wetlands.',
    habitat: 'Mangroves, wetlands, rivers, reed beds',
    typical_regions: ['Nepal (Terai)', 'India', 'Bangladesh', 'Southeast Asia'],
    ai_labels: ['fishing cat', 'Prionailurus viverrinus', 'Felis viverrinus'],
  },
  {
    common_name: 'Dhole',
    scientific_name: 'Cuon alpinus',
    category: 'mammal',
    rarity: 'rare',
    base_points: 70,
    iucn_status: 'EN',
    description: 'The Asian wild dog, hunting in packs. Can take down prey much larger than itself.',
    habitat: 'Tropical forests, alpine scrub',
    typical_regions: ['Nepal', 'India', 'Southeast Asia', 'China'],
    ai_labels: ['dhole', 'Cuon alpinus', 'Asian wild dog', 'Indian wild dog'],
  },
  {
    common_name: 'Himalayan Serow',
    scientific_name: 'Capricornis thar',
    category: 'mammal',
    rarity: 'rare',
    base_points: 60,
    iucn_status: 'NT',
    description: 'A goat-antelope of steep Himalayan forests and cliffs, with a mane of long dark hair.',
    habitat: 'Dense hill forests, steep rocky terrain',
    typical_regions: ['Nepal', 'India (Himalayan states)', 'Bhutan', 'China'],
    ai_labels: ['Himalayan serow', 'Capricornis thar', 'serow', 'thar'],
  },
  {
    common_name: 'Clouded Monitor',
    scientific_name: 'Varanus nebulosus',
    category: 'reptile',
    rarity: 'rare',
    base_points: 60,
    iucn_status: 'LC',
    description: 'A large, tree-climbing monitor lizard with a clouded pattern. More secretive than the Bengal monitor.',
    habitat: 'Dense tropical forests, bamboo groves',
    typical_regions: ['Nepal (eastern Terai)', 'Northeast India', 'Southeast Asia'],
    ai_labels: ['clouded monitor', 'Varanus nebulosus', 'clouded monitor lizard'],
  },
  {
    common_name: 'Sarus Crane',
    scientific_name: 'Antigone antigone',
    category: 'bird',
    rarity: 'rare',
    base_points: 65,
    iucn_status: 'VU',
    description: 'The world\'s tallest flying bird, standing up to 1.8 m. Known for lifelong pair bonds.',
    habitat: 'Wetlands, paddy fields, open floodplains',
    typical_regions: ['Nepal (Terai)', 'India', 'Southeast Asia'],
    ai_labels: ['sarus crane', 'Antigone antigone', 'Grus antigone', 'crane'],
  },

  // ── EPIC (6) ─────────────────────────────────────────────────────────────────
  {
    common_name: 'Snow Leopard',
    scientific_name: 'Panthera uncia',
    category: 'mammal',
    rarity: 'epic',
    base_points: 200,
    iucn_status: 'VU',
    description: 'The ghost of the mountains. A magnificent apex predator of high-altitude Himalayan terrain.',
    habitat: 'Alpine and subalpine zones, rocky terrain above 3000 m',
    typical_regions: ['Nepal', 'India (Ladakh, Sikkim)', 'Bhutan', 'China', 'Central Asia'],
    ai_labels: ['snow leopard', 'Panthera uncia', 'Uncia uncia', 'ounce'],
  },
  {
    common_name: 'Red Panda',
    scientific_name: 'Ailurus fulgens',
    category: 'mammal',
    rarity: 'epic',
    base_points: 200,
    iucn_status: 'EN',
    description: 'A charismatic rust-red mammal that feeds primarily on bamboo. The original "panda."',
    habitat: 'Temperate forests with dense bamboo undergrowth, 2200–4800 m',
    typical_regions: ['Nepal', 'India (Sikkim, Arunachal)', 'Bhutan', 'China', 'Myanmar'],
    ai_labels: ['red panda', 'Ailurus fulgens', 'firefox', 'lesser panda'],
  },
  {
    common_name: 'Clouded Leopard',
    scientific_name: 'Neofelis nebulosa',
    category: 'mammal',
    rarity: 'epic',
    base_points: 200,
    iucn_status: 'VU',
    description: 'A secretive, arboreal cat with unique cloud-like coat markings and the largest canine teeth relative to body size of any cat.',
    habitat: 'Tropical and subtropical forests',
    typical_regions: ['Nepal', 'India (northeastern states)', 'Southeast Asia', 'China'],
    ai_labels: ['clouded leopard', 'Neofelis nebulosa', 'clouded cat'],
  },
  {
    common_name: 'Himalayan Wolf',
    scientific_name: 'Canis lupus chanco',
    category: 'mammal',
    rarity: 'epic',
    base_points: 185,
    iucn_status: 'EN',
    description: 'A genetically distinct wolf from the high Himalayas, adapted to thin air above 4000 m.',
    habitat: 'High-altitude steppe, alpine meadows',
    typical_regions: ['Nepal (Mustang, Dolpo)', 'India (Ladakh, Spiti)', 'Tibet'],
    ai_labels: ['Himalayan wolf', 'Canis lupus chanco', 'Tibetan wolf', 'wolf'],
  },
  {
    common_name: 'Markhor',
    scientific_name: 'Capra falconeri',
    category: 'mammal',
    rarity: 'epic',
    base_points: 180,
    iucn_status: 'NT',
    description: 'Pakistan\'s national animal, with spectacular corkscrew horns. Listed on CITES Appendix I.',
    habitat: 'Mountain cliffs, forested ravines, rocky scrubland',
    typical_regions: ['Nepal (far northwest)', 'Pakistan', 'Afghanistan', 'India (Jammu)'],
    ai_labels: ['markhor', 'Capra falconeri', 'screw-horn goat'],
  },
  {
    common_name: 'Golden Eagle',
    scientific_name: 'Aquila chrysaetos',
    category: 'bird',
    rarity: 'epic',
    base_points: 175,
    iucn_status: 'LC',
    description: 'One of the most powerful raptors in the world. Rare in Nepal but seen hunting in high-altitude zones.',
    habitat: 'Mountains, open terrain, cliffs',
    typical_regions: ['Nepal', 'India (Himalayas)', 'Europe', 'North America'],
    ai_labels: ['golden eagle', 'Aquila chrysaetos', 'mountain eagle'],
  },

  // ── LEGENDARY (4) ────────────────────────────────────────────────────────────
  {
    common_name: 'Gangetic River Dolphin',
    scientific_name: 'Platanista gangetica',
    category: 'mammal',
    rarity: 'legendary',
    base_points: 500,
    iucn_status: 'EN',
    description: 'The national aquatic animal of India. Nearly blind and navigating by echolocation in muddy rivers.',
    habitat: 'Freshwater rivers — Ganges, Brahmaputra, and their tributaries',
    typical_regions: ['Nepal (Karnali, Narayani, Koshi rivers)', 'India', 'Bangladesh'],
    ai_labels: ['Ganges river dolphin', 'Platanista gangetica', 'susu', 'blind dolphin', 'river dolphin'],
  },
  {
    common_name: 'Irrawaddy Dolphin',
    scientific_name: 'Orcaella brevirostris',
    category: 'mammal',
    rarity: 'legendary',
    base_points: 500,
    iucn_status: 'EN',
    description: 'A stocky dolphin with a bulging forehead. Found in coastal and freshwater habitats in Southeast Asia.',
    habitat: 'Coastal, estuarine and freshwater rivers',
    typical_regions: ['Bangladesh', 'Myanmar', 'Cambodia', 'Laos'],
    ai_labels: ['Irrawaddy dolphin', 'Orcaella brevirostris', 'Mekong dolphin', 'Irrawaddy'],
  },
  {
    common_name: 'Wild Yak',
    scientific_name: 'Bos mutus',
    category: 'mammal',
    rarity: 'legendary',
    base_points: 500,
    iucn_status: 'VU',
    description: 'A massive bovid of the Tibetan Plateau, surviving extreme cold and altitude. Wild populations are rare.',
    habitat: 'High-altitude alpine tundra, barren plateaus above 4000 m',
    typical_regions: ['Nepal (Dolpo, Mustang)', 'Tibet', 'India (Ladakh)'],
    ai_labels: ['wild yak', 'Bos mutus', 'yak'],
  },
  {
    common_name: 'Sumatran Rhinoceros',
    scientific_name: 'Dicerorhinus sumatrensis',
    category: 'mammal',
    rarity: 'legendary',
    base_points: 500,
    iucn_status: 'CR',
    description: 'The smallest and most ancient rhinoceros species, with fewer than 80 individuals remaining. Critically endangered and extremely rarely photographed.',
    habitat: 'Dense tropical highland forests',
    typical_regions: ['Indonesia (Sumatra, Borneo)', 'Malaysia (historical range includes South Asia borders)'],
    ai_labels: ['Sumatran rhinoceros', 'Dicerorhinus sumatrensis', 'hairy rhinoceros', 'Asian two-horned rhino'],
  },
];

async function seed() {
  console.log('Connecting to database...');
  try {
    await db.query('SELECT 1');
  } catch (err) {
    console.error('Database connection failed:', err.message);
    process.exit(1);
  }

  console.log(`Seeding ${animals.length} animals...`);
  let inserted = 0;
  let skipped = 0;

  for (const animal of animals) {
    try {
      const existing = await db.query(
        'SELECT id FROM animals WHERE lower(scientific_name) = lower($1)',
        [animal.scientific_name]
      );
      if (existing.rows.length > 0) {
        skipped++;
        continue;
      }

      await db.query(
        `INSERT INTO animals
           (common_name, scientific_name, category, rarity, base_points, iucn_status,
            description, habitat, typical_regions, ai_labels)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)`,
        [
          animal.common_name,
          animal.scientific_name,
          animal.category,
          animal.rarity,
          animal.base_points,
          animal.iucn_status,
          animal.description,
          animal.habitat,
          animal.typical_regions,
          animal.ai_labels,
        ]
      );
      inserted++;
      console.log(`  ✓ [${animal.rarity.padEnd(10)}] ${animal.common_name}`);
    } catch (err) {
      console.error(`  ✗ Failed to insert ${animal.common_name}:`, err.message);
    }
  }

  // Seed achievements
  const { seedAchievements } = require('../services/achievementService');
  await seedAchievements();
  console.log('  ✓ Achievements seeded');

  console.log(`\nDone! Inserted: ${inserted}, Skipped (already existed): ${skipped}`);
  await db.pool.end();
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
